# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: 🌧️ Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # see https://github.com/marketplace/actions/redocly-cli-github-action
      - name: Redocly CLI Build docs
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: 'join docs/test/hello-v1.json docs/test/hello-v2.json -o openapi.json'

      # see https://github.com/marketplace/actions/redocly-cli-github-action
      - name: Redocly CLI Build docs
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: 'build-docs openapi.json -o openapi.html'

      # see https://github.com/marketplace/actions/commit-with-deploy-key
      - name: 🚀 Deploy Docs
        uses: leigholiver/commit-with-deploy-key@v1.0.4
        with:
          source: openapi.html
          destination_folder: html/test
          destination_repo: this-is-spear/hello-docs-checker
          destination_branch: docs
          deploy_key: ${{ secrets.DEP_KEY }}
